#CodeEmailMKT.Domain.Entity.Customer.dcm.yml
CodeEmailMKT\Domain\Entity\Customer:
  type: entity
  repositoryClass: CodeEmailMKT\Infrastructure\Persistence\Doctrine\Repository\CampaignRepository
  table: campaigns
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
        type: string
        length: 200
    template:
        type: text
  manyToMany:
      tags:
        targetEntity: CodeEmailMKT\Domain\Entity\Tag
        mappedBy: campaigns